version: "3"

services:
  server:
    image: node:20
    container_name: server-app
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    restart: always
    working_dir: /server
    volumes:
      - ../:/server
      - ../.env:/server/.env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgresql
    networks:
      - pp

  postgresql:
    image: postgres:16
    container_name: psql-app
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  pp:

volumes:
  postgres_data:
